version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
      - run: npm ci
      - save_cache:
          key: 'dependency-cache-{{ checksum "package.json" }}'
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
